subgraphs:
  customers:
    routing_url: https://mesh.ocrateris.cloud/service/customers
    schema:
      subgraph_url: https://mesh.ocrateris.cloud/service/customers
  products:
    routing_url: https://mesh.ocrateris.cloud/service/products
    schema:
      subgraph_url: https://mesh.ocrateris.cloud/service/products
  reviews:
    routing_url: https://mesh.ocrateris.cloud/service/reviews
    schema:
      subgraph_url: https://mesh.ocrateris.cloud/service/reviews